import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { locales } from "@/navigation";
import { notFound } from "next/navigation";
import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import ThemeDataProvider from "@/context/theme-data-provider";
const vazirFont = localFont({
  src: "../fonts/Vazirmatn[wght].woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  if (!locales.includes(locale)) {
    notFound();
  }

  const messages = useMessages();

  return (
    <html lang={locale}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <body className={`${vazirFont.className} antialiase`}>
            <ThemeDataProvider>
              <Navbar locale={locale} />
              {children}
            </ThemeDataProvider>
          </body>
        </ThemeProvider>
      </NextIntlClientProvider>
    </html>
  );
}
