import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { locales } from "@/navigation";
import { notFound } from "next/navigation";
import Navbar from "@/components/navbar";
import { Toaster } from "sonner";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import Providers from "./providers";
import { Toaster as ShadCnToaster} from "@/components/ui/toaster"
const vazirFont = localFont({
  src: "../fonts/Vazirmatn[wght].woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  if (!locales.includes(locale)) {
    notFound();
  }

  const messages = useMessages();

  return (
    <html lang={locale}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <Providers>
          <body className={`${vazirFont.className} antialiase overflow-hidden`}>
            <Navbar locale={locale} />
            <SidebarProvider className={locale === "fa" ? "rtl" : ""}>
              <AppSidebar />
              <main className="w-full h-full">
                <SidebarTrigger />
                {children}
              </main>
            </SidebarProvider>
            <Toaster />
            <ShadCnToaster/>
          </body>
        </Providers>
      </NextIntlClientProvider>
    </html>
  );
}
